# Generated by Django 4.0.4 on 2022-05-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prive',
            new_name='price',
        ),
    ]
